[package]
name = "pravera-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
pravera-core.workspace = true
pravera-proto.workspace = true
pravera-audio.workspace = true
pravera-codec.workspace = true
pravera-files.workspace = true
pravera-transport.workspace = true
pravera-discovery.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
